/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as CreateEnergyNFTScriptJson } from "../CreateEnergyNFT.ral.json";

export const CreateEnergyNFT = new ExecutableScript<{
  contractOwner: Address;
  initialEnergy: bigint;
  initialPrice: bigint;
  nftId: HexString;
}>(Script.fromJson(CreateEnergyNFTScriptJson, "", []), getContractByCodeHash);
